docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - Introduction: intro.md
    - Reference:
      - Specifications: specs.md
      - "File Upload Input": file-input.md
      - "Optional Input Filters": optional-input-filters.md
      - "Unfiltered Data": unfiltered-data.md
    - "Application Integration":
        - "Usage in a laminas-mvc application": application-integration/usage-in-a-laminas-mvc-application.md
        - "Usage in a mezzio application": application-integration/usage-in-a-mezzio-application.md
site_name: laminas-inputfilter
site_description: 'Normalize and validate input sets from the web, APIs, the CLI, and more, including files.'
repo_url: 'https://github.com/laminas/laminas-inputfilter'
